### PR TITLE
Feature: volcano plot tool

### PR DESCRIPTION
**Pull request by saksham219**
Adds a volcano plot tool.

Volcano plot is made only after differential expression has been done and columns 'logFC' and 'adj.P.Val' are available. The plot is colored red and blue according to cutoffs that can be set. 
Support for shapes, sizes and tooltips based on row metadata.

### CODE REVIEW

**Comment by assaron** [comment]
Thanks for the PR. Here are several comments.

Major:

- The plot should support DESeq2 output too, which has different names. The best way I see it is the following: there is an option to chose the p-value column (which will also support any other way to get them, including loading from files or whatever). In case there is one of the standard columns (like from limma or DESeq2) the column should be selected automatically.
- There should be an option to export the plot to SVG (see other plots for examples).

Minor:
- The plot is slow due to high number of points. Is there a way, how to make it work faster? May be using webgl, or rendering some parts as PNG.
- Would be great to have an option to show labels for the top regulated genes. Probably the best way to do this would be to add an checkbox for showing labels for the genes, selected in the heatmap interface, which will be very flexible.
- I would move size and shape into advanced options - I don't see many example, when this would be useful. Ffor example, see how adjust methods are done in row profile chart.

**Comment by saksham219** [comment]
Hi Alexey

Most of the comments have been incorporated. 

- The plot is now made using webgl which has increased rendering speed considerably.
- It can handle both DEseq and limma outputs and also gives options for choosing p-val and logFC columns.
- Selected rows in the heatmap interface can be used to label points.
- svg can be downloaded
- Size and shape have been moved into advanced options.

The only thing left is the ability to add a file for p-values and logFCs. This seems like an advanced feature to me which I will continue working on after some other features are addressed. Let me know if that is okay and the tool is in a condition to be released.

**Comment by assaron** [comment]
Wow, WebGL works fantastically!

Small things I think should be fixed:
* Labels for the selected genes should be updated online on selection (so that I can change the highlighted genes using search, filter or whatever).
* Axis labels are switched between X and Y.
* Let's set log2fc default threshold to 1, not 2. 
* Does SVG really works for you? For me it shows an empty grid.

**Comment by saksham219** [comment]
Made changes for the above 4 things except the svg. I also see a blank plot when downloading it. When I try it without using webgl it works fine. I'm figuring out how to save the svg from a webgl enabled plot.

**Comment by assaron** [comment]
Small bug: "Adjusted p value significance" should be changed to "P value significance", as it can be nominal P-value (so refer just to the option).

Also:
> The only thing left is the ability to add a file for p-values and logFCs. 

I meant that the expression table with annotations can come from wherever. Currently it works perfectly, as I expected.

For svg: got it. There is an gl-container div with canvas just adjacent to svg, probably, the bitmap image can be somehow incorporated from there. It also would be nice to try to have the canvas to have higher dpi, so that it's proper publication quality.

And another thing, can you incorporate repel labeling algorithm for the labels, such as here:  https://github.com/ctlab/phantasus.js/commit/9504914a4cb2a925b2b06dd3825946869a7b15ff ? So that the gene labels don't overlap.

**Comment by assaron** [comment]
Yeah, there is an option to convert canvas to base64 png image: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL And I believe it later can be added to svg with an image tag.

And another potentially useful link: https://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf

**Comment by saksham219** [comment]
Thanks for those references. They were helpful. I am currently embedding the base64 png into the svg div and then creating a blob. This seems to work fine, although I'm not sure if this is the best way.

For the labeling, when I tried the d3 labeler implemented in 'plotly.annotate.js' the browser hanged. I suppose this is because the labeler is trying to repel the points and labels and since there are a lot of points, it might be very computationally expensive. I will have to figure out an annotate function which only repels the labels while considering the points as background.  

The rest of the things have been taken care of.

**Comment by assaron** [comment]
Cool! May be it's not perfect, but it works fine, indeed. And actually, we do something similar with volcano plots in R, rasterizing the points and having the vector graphics just for the labels and other stuff, so that Inkscape/Illustrator doesn't hang on such figures.

I found a small bug, that the labels or disappearing when the plot is redrawn. To reproduce: do a plot with labels, change P value column. The plot is redrawn and the labels disappear. Seems to be the case for P value, logFC column selection and the thresholds.

Otherwise I think it's ready to be merged. I'll just add labeling and higher quality SVGs as separate issues, if you are not sure how to do them now.

**Comment by saksham219** [comment]
The bug has been fixed.

That sounds good!. I'll be able to revisit those issues when I get more familiar with how labeling is working in d3.js.

**Comment by assaron** [comment]
Actually, it breaks phantomjs tests: https://travis-ci.org/ctlab/phantasus/jobs/627802041

The error happens due to this `let` usage: https://github.com/ctlab/phantasus.js/blob/ef203aadd63b4dee46e236c4d7e5e9b4ae9d80be/src/tools/volcano_tool.js#L320 Should it be changed to `var`?

**Pull request merged**
